version: '3.9'

services:
  db:
    image: ${DB_IMAGE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${LOCAL_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: websockets-db
